var _ = require('lodash');

var popupTpl = _.template([
    '<key>Popovers</key>',
    '<array>',
        '<dict>',
            '<key>Filename</key>',
            '<string><%= popupRes %></string>',
            '<key>Identifier</key>',
            '<string>kango-ui-popup</string>',
        '</dict>',
    '</array>',
    '<key>Toolbar Items</key>',
    '<array>',
        '<dict>',
            '<key>Command</key>',
            '<string></string>',
            '<key>Identifier</key>',
            '<string>kango-ui-button</string>',
            '<key>Image</key>',
            '<string>static/toolbar_button/inactive.png</string>',
            '<key>Include By Default</key>',
            '<true/>',
            '<key>Label</key>',
            '<string><%= title %></string>',
            '<key>Popover</key>',
            '<string>kango-ui-popup</string>',
            '<key>Tool Tip</key>',
            '<string><%= title %></string>',
        '</dict> ',
    '</array>'
].join('\n'));

var tpl = _.template([
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
        '<dict>',
            '<key>Author</key>',
            '<string><%= author %></string>',
            '<key>CFBundleDisplayName</key>',
            '<string><%= title %></string>',
            '<key>CFBundleIdentifier</key>',
            '<string><%= extensionId %></string>',
            '<key>CFBundleInfoDictionaryVersion</key>',
            '<string>6.0</string>',
            '<key>CFBundleShortVersionString</key>',
            '<string><%= version %></string>',
            '<key>CFBundleVersion</key>',
            '<string><%= version %></string>',
            '<key>Chrome</key>',
            '<dict>',
                '<key>Database Quota</key>',
                '<real>10485760</real>',
                '<key>Global Page</key>',
                '<string>background.html</string>',
                '<%= popovers %>',
            '</dict>',
            '<key>Content</key>',
            '<dict>',
                '<key>Scripts</key>',
                '<dict>',
                    '<key>Start</key>',
                    '<array>',
                        '<string>includes/content.js</string>',
                    '</array>',
                '</dict>',
                '<key>Whitelist</key>',
                '<array>',
                    '<string>http://*/*</string>',
                    '<string>https://*/*</string>',
                '</array>',
            '</dict>',
            '<key>Description</key>',
            '<string><%= description %></string>',
            '<key>ExtensionInfoDictionaryVersion</key>',
            '<string>1.0</string>',
            '<key>Permissions</key>',
            '<dict>',
                '<key>Website Access</key>',
                '<dict>',
                    '<key>Include Secure Pages</key>',
                    '<true/>',
                    '<key>Level</key>',
                    '<string>All</string>',
                '</dict>',
            '</dict>',
            '<key>Update Manifest URL</key>',
            '<string><%= updateUrl %></string>',
            '<key>Website</key>',
            '<string><%= homepageUrl %></string>',
        '</dict>',
    '</plist>'
].join('\n'));

module.exports = function(config) {
    return tpl({
        title: config.title,
        author: config.author,
        description: config.description,
        extensionId: config.safari.extensionId,
        updateUrl: config.safari.updateUrl,
        homepageUrl: config.homepageUrl,
        version: config.version,
        popovers: config.popupRes ? popupTpl({
            title: config.title,
            popupRes: config.popupRes
        }) : ''
    });
};
